
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class BeliMotor extends javax.swing.JFrame {

    /**
     * Creates new form BeliMotor
     */
    public BeliMotor() {
        initComponents();
        search2();
    }
    public void search2()
    {
        
        String[][]data = {
            {"Jakarta","DKI Jakarta","HONDA SC","Jl.Mangga"},
            {"Bandung","Jawa Barat","HONDA SC","Jl.Sunda"},
            {"Semarang","Jawa Tengah","HONDA APS","Jl.Sriwijaya"},
            {"Surabaya","Jawa Timur","HONDA APS","Jl.A.Dahlan"},
            {"Malang","Jawa Timur","HONDA SC","Jl.Penirama"},
            {"Jambi","Jambi","HONDA APS","Jl.Hadiri"},
        };
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        for(String[]row :data){
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlKiriMotor = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        BtnHome = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        BtnPromo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btn_Service = new javax.swing.JButton();
        PanelMotor = new javax.swing.JPanel();
        PanelMotor1 = new javax.swing.JPanel();
        BtnNext1 = new javax.swing.JButton();
        InfoMotor1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        PanelMotor2 = new javax.swing.JPanel();
        BtnNext2 = new javax.swing.JButton();
        BtnBack2 = new javax.swing.JButton();
        InfoMotor2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        PanelMotor3 = new javax.swing.JPanel();
        BtnNext3 = new javax.swing.JButton();
        BtnBack3 = new javax.swing.JButton();
        InfoMotor3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PanelMotor4 = new javax.swing.JPanel();
        BtnNext4 = new javax.swing.JButton();
        BtnBack4 = new javax.swing.JButton();
        InfoMotor4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        PanelMotor5 = new javax.swing.JPanel();
        BtnBack5 = new javax.swing.JButton();
        InfoMotor5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        panelinfo1 = new javax.swing.JPanel();
        btnmesin1 = new javax.swing.JButton();
        btndimensi1 = new javax.swing.JButton();
        btnrangka1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        panelinfo2 = new javax.swing.JPanel();
        btnmesin2 = new javax.swing.JButton();
        btndimensi2 = new javax.swing.JButton();
        btnrangka2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area2 = new javax.swing.JTextArea();
        btnkembali2 = new javax.swing.JButton();
        panelinfo3 = new javax.swing.JPanel();
        btnmesin3 = new javax.swing.JButton();
        btndimensi3 = new javax.swing.JButton();
        btnrangka3 = new javax.swing.JButton();
        txt_area3 = new javax.swing.JScrollPane();
        txtarea3 = new javax.swing.JTextArea();
        btnkembali3 = new javax.swing.JButton();
        panelinfo4 = new javax.swing.JPanel();
        btnmesin4 = new javax.swing.JButton();
        btndimensi4 = new javax.swing.JButton();
        btnrangka4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtarea4 = new javax.swing.JTextArea();
        btnkembali4 = new javax.swing.JButton();
        panelinfo5 = new javax.swing.JPanel();
        btnmesin5 = new javax.swing.JButton();
        btndimensi5 = new javax.swing.JButton();
        btnrangka5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area5 = new javax.swing.JTextArea();
        btnkembali5 = new javax.swing.JButton();
        panelsearch = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_cari = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HONDA.com");

        PnlKiriMotor.setBackground(new java.awt.Color(0, 0, 0));

        panel.setBackground(new java.awt.Color(255, 255, 255));

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1111111.png"))); // NOI18N
        BtnHome.setText("HOME");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15151.png"))); // NOI18N
        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });

        BtnPromo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/123456.png"))); // NOI18N
        BtnPromo.setText("PESAN");
        BtnPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPromoActionPerformed(evt);
            }
        });

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/aa3.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Bodoni Bk BT", 1, 24)); // NOI18N
        jLabel17.setText("HONDA");

        jLabel18.setFont(new java.awt.Font("Bodoni Bk BT", 1, 24)); // NOI18N
        jLabel18.setText("HEART");

        jLabel19.setFont(new java.awt.Font("Bodoni Bk BT", 1, 24)); // NOI18N
        jLabel19.setText("ONE");

        btn_Service.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/2211111.png"))); // NOI18N
        btn_Service.setText("SERVICE");
        btn_Service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(8, 8, 8))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel19))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnPromo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Service, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BtnHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(33, 33, 33)
                .addComponent(BtnPromo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Service, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel16)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        PanelMotor.setLayout(new java.awt.CardLayout());

        PanelMotor1.setBackground(new java.awt.Color(255, 255, 255));

        BtnNext1.setText("NEXT");
        BtnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNext1ActionPerformed(evt);
            }
        });

        InfoMotor1.setText("Info Motor");
        InfoMotor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMotor1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/Honda-CB1100.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel8.setText("1. CB1100-RS");

        jLabel9.setFont(new java.awt.Font("Bodoni Bk BT", 1, 16)); // NOI18N
        jLabel9.setText("Rp 135.500.000");

        javax.swing.GroupLayout PanelMotor1Layout = new javax.swing.GroupLayout(PanelMotor1);
        PanelMotor1.setLayout(PanelMotor1Layout);
        PanelMotor1Layout.setHorizontalGroup(
            PanelMotor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNext1)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoMotor1)
                .addGap(18, 18, 18))
            .addGroup(PanelMotor1Layout.createSequentialGroup()
                .addGroup(PanelMotor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMotor1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMotor1Layout.setVerticalGroup(
            PanelMotor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor1Layout.createSequentialGroup()
                .addGroup(PanelMotor1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor1Layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(35, 35, 35))
                    .addGroup(PanelMotor1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(InfoMotor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(BtnNext1)
                .addGap(25, 25, 25))
        );

        PanelMotor.add(PanelMotor1, "card2");

        PanelMotor2.setBackground(new java.awt.Color(255, 255, 255));

        BtnNext2.setText("NEXT");
        BtnNext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNext2ActionPerformed(evt);
            }
        });

        BtnBack2.setText("BACK");
        BtnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack2ActionPerformed(evt);
            }
        });

        InfoMotor2.setText("Info Motor");
        InfoMotor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMotor2ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/Honda-All-New-CBR-150R.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bodoni Bk BT", 1, 16)); // NOI18N
        jLabel10.setText("Rp 35.500.000");

        jLabel11.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel11.setText("2. CBR150R STD");

        javax.swing.GroupLayout PanelMotor2Layout = new javax.swing.GroupLayout(PanelMotor2);
        PanelMotor2.setLayout(PanelMotor2Layout);
        PanelMotor2Layout.setHorizontalGroup(
            PanelMotor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BtnBack2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNext2)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoMotor2)
                .addGap(18, 18, 18))
            .addGroup(PanelMotor2Layout.createSequentialGroup()
                .addGroup(PanelMotor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelMotor2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMotor2Layout.setVerticalGroup(
            PanelMotor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor2Layout.createSequentialGroup()
                .addGroup(PanelMotor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor2Layout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(PanelMotor2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(InfoMotor2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelMotor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNext2)
                    .addComponent(BtnBack2))
                .addGap(25, 25, 25))
        );

        PanelMotor.add(PanelMotor2, "card2");

        PanelMotor3.setBackground(new java.awt.Color(255, 255, 255));

        BtnNext3.setText("NEXT");
        BtnNext3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNext3ActionPerformed(evt);
            }
        });

        BtnBack3.setText("BACK");
        BtnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack3ActionPerformed(evt);
            }
        });

        InfoMotor3.setText("Info Motor");
        InfoMotor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMotor3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/Honda-CB500X.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Bodoni Bk BT", 1, 16)); // NOI18N
        jLabel6.setText("Rp.189.500.000");

        jLabel7.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel7.setText("3. CB500X");

        javax.swing.GroupLayout PanelMotor3Layout = new javax.swing.GroupLayout(PanelMotor3);
        PanelMotor3.setLayout(PanelMotor3Layout);
        PanelMotor3Layout.setHorizontalGroup(
            PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BtnBack3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNext3)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InfoMotor3)
                .addGap(18, 18, 18))
            .addGroup(PanelMotor3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelMotor3Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );
        PanelMotor3Layout.setVerticalGroup(
            PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor3Layout.createSequentialGroup()
                .addGroup(PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor3Layout.createSequentialGroup()
                        .addContainerGap(88, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33))
                    .addGroup(PanelMotor3Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(InfoMotor3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNext3)
                    .addComponent(BtnBack3))
                .addGap(25, 25, 25))
            .addGroup(PanelMotor3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelMotor3Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel7)
                    .addContainerGap(308, Short.MAX_VALUE)))
        );

        PanelMotor.add(PanelMotor3, "card2");

        PanelMotor4.setBackground(new java.awt.Color(255, 255, 255));

        BtnNext4.setText("NEXT");
        BtnNext4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNext4ActionPerformed(evt);
            }
        });

        BtnBack4.setText("BACK");
        BtnBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack4ActionPerformed(evt);
            }
        });

        InfoMotor4.setText("Info Motor");
        InfoMotor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMotor4ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/Honda-All-New-CB-150R.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel12.setText("4. CB150R Streetfire");

        jLabel14.setFont(new java.awt.Font("Bodoni Bk BT", 1, 16)); // NOI18N
        jLabel14.setText("Rp 29.500.000");

        javax.swing.GroupLayout PanelMotor4Layout = new javax.swing.GroupLayout(PanelMotor4);
        PanelMotor4.setLayout(PanelMotor4Layout);
        PanelMotor4Layout.setHorizontalGroup(
            PanelMotor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(BtnBack4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnNext4)
                .addGap(24, 24, 24))
            .addGroup(PanelMotor4Layout.createSequentialGroup()
                .addGroup(PanelMotor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(InfoMotor4)
                .addGap(18, 18, 18))
            .addGroup(PanelMotor4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMotor4Layout.setVerticalGroup(
            PanelMotor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor4Layout.createSequentialGroup()
                .addGroup(PanelMotor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor4Layout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35))
                    .addGroup(PanelMotor4Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(InfoMotor4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelMotor4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnNext4)
                    .addComponent(BtnBack4))
                .addGap(25, 25, 25))
        );

        PanelMotor.add(PanelMotor4, "card2");

        PanelMotor5.setBackground(new java.awt.Color(255, 255, 255));

        BtnBack5.setText("BACK");
        BtnBack5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBack5ActionPerformed(evt);
            }
        });

        InfoMotor5.setText("Info Motor");
        InfoMotor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoMotor5ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/11.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Bodoni Bk BT", 1, 18)); // NOI18N
        jLabel13.setText("5. CB300R ");

        jLabel15.setFont(new java.awt.Font("Bodoni Bk BT", 1, 16)); // NOI18N
        jLabel15.setText("Rp 75.000.000");

        javax.swing.GroupLayout PanelMotor5Layout = new javax.swing.GroupLayout(PanelMotor5);
        PanelMotor5.setLayout(PanelMotor5Layout);
        PanelMotor5Layout.setHorizontalGroup(
            PanelMotor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMotor5Layout.createSequentialGroup()
                .addGroup(PanelMotor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMotor5Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InfoMotor5)
                .addGap(18, 18, 18))
            .addGroup(PanelMotor5Layout.createSequentialGroup()
                .addGroup(PanelMotor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BtnBack5))
                    .addGroup(PanelMotor5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMotor5Layout.setVerticalGroup(
            PanelMotor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMotor5Layout.createSequentialGroup()
                .addGroup(PanelMotor5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMotor5Layout.createSequentialGroup()
                        .addContainerGap(58, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15)
                        .addGap(30, 30, 30))
                    .addGroup(PanelMotor5Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(InfoMotor5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(BtnBack5)
                .addGap(25, 25, 25))
        );

        PanelMotor.add(PanelMotor5, "card2");

        panelinfo1.setBackground(new java.awt.Color(255, 255, 255));

        btnmesin1.setText("MESIN");
        btnmesin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmesin1ActionPerformed(evt);
            }
        });

        btndimensi1.setText("DIMENSI");
        btndimensi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndimensi1ActionPerformed(evt);
            }
        });

        btnrangka1.setText("RANGKA");
        btnrangka1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangka1ActionPerformed(evt);
            }
        });

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane1.setViewportView(txt_area);

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelinfo1Layout = new javax.swing.GroupLayout(panelinfo1);
        panelinfo1.setLayout(panelinfo1Layout);
        panelinfo1Layout.setHorizontalGroup(
            panelinfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo1Layout.createSequentialGroup()
                .addGroup(panelinfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfo1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(panelinfo1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelinfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndimensi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmesin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrangka1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelinfo1Layout.setVerticalGroup(
            panelinfo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfo1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnmesin1)
                .addGap(18, 18, 18)
                .addComponent(btndimensi1)
                .addGap(27, 27, 27)
                .addComponent(btnrangka1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addGap(17, 17, 17))
        );

        PanelMotor.add(panelinfo1, "card7");

        panelinfo2.setBackground(new java.awt.Color(255, 255, 255));

        btnmesin2.setText("MESIN");
        btnmesin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmesin2ActionPerformed(evt);
            }
        });

        btndimensi2.setText("DIMENSI");
        btndimensi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndimensi2ActionPerformed(evt);
            }
        });

        btnrangka2.setText("RANGKA");
        btnrangka2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangka2ActionPerformed(evt);
            }
        });

        txt_area2.setColumns(20);
        txt_area2.setRows(5);
        jScrollPane2.setViewportView(txt_area2);

        btnkembali2.setText("BACK");
        btnkembali2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembali2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelinfo2Layout = new javax.swing.GroupLayout(panelinfo2);
        panelinfo2.setLayout(panelinfo2Layout);
        panelinfo2Layout.setHorizontalGroup(
            panelinfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo2Layout.createSequentialGroup()
                .addGroup(panelinfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfo2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkembali2))
                    .addGroup(panelinfo2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelinfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndimensi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmesin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrangka2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelinfo2Layout.setVerticalGroup(
            panelinfo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfo2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnmesin2)
                .addGap(18, 18, 18)
                .addComponent(btndimensi2)
                .addGap(27, 27, 27)
                .addComponent(btnrangka2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkembali2)
                .addGap(17, 17, 17))
        );

        PanelMotor.add(panelinfo2, "card7");

        panelinfo3.setBackground(new java.awt.Color(255, 255, 255));

        btnmesin3.setText("MESIN");
        btnmesin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmesin3ActionPerformed(evt);
            }
        });

        btndimensi3.setText("DIMENSI");
        btndimensi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndimensi3ActionPerformed(evt);
            }
        });

        btnrangka3.setText("RANGKA");
        btnrangka3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangka3ActionPerformed(evt);
            }
        });

        txtarea3.setColumns(20);
        txtarea3.setRows(5);
        txt_area3.setViewportView(txtarea3);

        btnkembali3.setText("BACK");
        btnkembali3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembali3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelinfo3Layout = new javax.swing.GroupLayout(panelinfo3);
        panelinfo3.setLayout(panelinfo3Layout);
        panelinfo3Layout.setHorizontalGroup(
            panelinfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo3Layout.createSequentialGroup()
                .addGroup(panelinfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfo3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkembali3))
                    .addGroup(panelinfo3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelinfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndimensi3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmesin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrangka3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_area3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelinfo3Layout.setVerticalGroup(
            panelinfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfo3Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnmesin3)
                .addGap(18, 18, 18)
                .addComponent(btndimensi3)
                .addGap(27, 27, 27)
                .addComponent(btnrangka3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo3Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(txt_area3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkembali3)
                .addGap(17, 17, 17))
        );

        PanelMotor.add(panelinfo3, "card7");

        panelinfo4.setBackground(new java.awt.Color(255, 255, 255));

        btnmesin4.setText("MESIN");
        btnmesin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmesin4ActionPerformed(evt);
            }
        });

        btndimensi4.setText("DIMENSI");
        btndimensi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndimensi4ActionPerformed(evt);
            }
        });

        btnrangka4.setText("RANGKA");
        btnrangka4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangka4ActionPerformed(evt);
            }
        });

        txtarea4.setColumns(20);
        txtarea4.setRows(5);
        jScrollPane4.setViewportView(txtarea4);

        btnkembali4.setText("BACK");
        btnkembali4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembali4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelinfo4Layout = new javax.swing.GroupLayout(panelinfo4);
        panelinfo4.setLayout(panelinfo4Layout);
        panelinfo4Layout.setHorizontalGroup(
            panelinfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo4Layout.createSequentialGroup()
                .addGroup(panelinfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfo4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkembali4))
                    .addGroup(panelinfo4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelinfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndimensi4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmesin4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrangka4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelinfo4Layout.setVerticalGroup(
            panelinfo4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfo4Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnmesin4)
                .addGap(18, 18, 18)
                .addComponent(btndimensi4)
                .addGap(27, 27, 27)
                .addComponent(btnrangka4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkembali4)
                .addGap(17, 17, 17))
        );

        PanelMotor.add(panelinfo4, "card7");

        panelinfo5.setBackground(new java.awt.Color(255, 255, 255));

        btnmesin5.setText("MESIN");
        btnmesin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmesin5ActionPerformed(evt);
            }
        });

        btndimensi5.setText("DIMENSI");
        btndimensi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndimensi5ActionPerformed(evt);
            }
        });

        btnrangka5.setText("RANGKA");
        btnrangka5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrangka5ActionPerformed(evt);
            }
        });

        txt_area5.setColumns(20);
        txt_area5.setRows(5);
        jScrollPane3.setViewportView(txt_area5);

        btnkembali5.setText("BACK");
        btnkembali5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembali5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelinfo5Layout = new javax.swing.GroupLayout(panelinfo5);
        panelinfo5.setLayout(panelinfo5Layout);
        panelinfo5Layout.setHorizontalGroup(
            panelinfo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo5Layout.createSequentialGroup()
                .addGroup(panelinfo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelinfo5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnkembali5))
                    .addGroup(panelinfo5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelinfo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btndimensi5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmesin5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnrangka5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        panelinfo5Layout.setVerticalGroup(
            panelinfo5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfo5Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btnmesin5)
                .addGap(18, 18, 18)
                .addComponent(btndimensi5)
                .addGap(27, 27, 27)
                .addComponent(btnrangka5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelinfo5Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnkembali5)
                .addGap(17, 17, 17))
        );

        PanelMotor.add(panelinfo5, "card7");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "KOTA", "PROVINSI", "STATUS", "ALAMAT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable1);

        txt_cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cariKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("CARI");

        jLabel21.setFont(new java.awt.Font("Bodoni Bk BT", 1, 12)); // NOI18N
        jLabel21.setText("INFO TEMPAT SERVICE MOTOR");

        javax.swing.GroupLayout panelsearchLayout = new javax.swing.GroupLayout(panelsearch);
        panelsearch.setLayout(panelsearchLayout);
        panelsearchLayout.setHorizontalGroup(
            panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelsearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addGroup(panelsearchLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsearchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(79, 79, 79))
        );
        panelsearchLayout.setVerticalGroup(
            panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsearchLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(panelsearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        PanelMotor.add(panelsearch, "card12");

        javax.swing.GroupLayout PnlKiriMotorLayout = new javax.swing.GroupLayout(PnlKiriMotor);
        PnlKiriMotor.setLayout(PnlKiriMotorLayout);
        PnlKiriMotorLayout.setHorizontalGroup(
            PnlKiriMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlKiriMotorLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(PanelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PnlKiriMotorLayout.setVerticalGroup(
            PnlKiriMotorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlKiriMotorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnlKiriMotorLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(PanelMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlKiriMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlKiriMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
        home n= new home();
        n.setVisible(true);
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        int dialogBtn = JOptionPane.OK_CANCEL_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin Akan Keluar?","PERINGATAN",dialogBtn);
        if (dialogResult==0){
            System.exit(0);
        }else{
        }              // TODO add your handling code here:
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPromoActionPerformed
        // TODO add your handling code here:
        PesanMotor2 n= new PesanMotor2();
        n.setVisible(true);

    }//GEN-LAST:event_BtnPromoActionPerformed

    private void InfoMotor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMotor2ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelinfo2);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_InfoMotor2ActionPerformed

    private void BtnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNext1ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor2);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnNext1ActionPerformed

    private void BtnNext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNext2ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor3);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnNext2ActionPerformed

    private void BtnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack2ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor1);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnBack2ActionPerformed

    private void BtnNext3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNext3ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor4);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnNext3ActionPerformed

    private void BtnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack3ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor2);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnBack3ActionPerformed

    private void BtnNext4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNext4ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor5);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnNext4ActionPerformed

    private void BtnBack4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack4ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor3);
            PanelMotor.repaint();
            PanelMotor.revalidate();    
    }//GEN-LAST:event_BtnBack4ActionPerformed

    private void BtnBack5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBack5ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor4);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_BtnBack5ActionPerformed

    private void btnmesin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmesin1ActionPerformed
        // TODO add your handling code here:
        txt_area.setText("Tipe Mesin\t:In Line Four-Cylinder,air and oli-cooled,DOHC"  
                +"\nKapasitas Silinder :1140cc" +"\nDiameter x Rangka :73.5 x 67.2 mm" 
                +"\nRasio Kompresi :9.5 : 1" +"\nDaya Maksimum :66kW/7,500 rpm" 
                +"\nTorsi Maksimum :91 Nm/5,500 rpm" +"\nSistem Starter\t:Electric" 
                +"\nTransmisi\t:6 Kecepatan" +"\nType Kopling\t:Wet, Multiplate"
                +"\nSistem Bahan Bakar :PGM-FI electronic fuel injection");
    }//GEN-LAST:event_btnmesin1ActionPerformed

    private void btnrangka1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangka1ActionPerformed
        txt_area.setText("Tipe Rangka :Double Steel Cradle"  
                +"\nSuspensi Depan:43 mm conventional fork(SDBV)with udjustable spring preload"
                +"\nSuspendi Belakang :Twin Shocks with udjustable spring preload"
                +"\nVelg Depan :17in x 3.50MT 10-Spoke diecast alumunium" 
                +"\nVelg Belakang :17in x 5.50MT 10-Spoke diecast alumunium" 
                +"\nBan Depan :120/70 R17" +"\nBan Belakang :180/55 R17" 
                +"\nRem Depan : Double Disc"+"\nRem Belakang : Single Disc");
    }//GEN-LAST:event_btnrangka1ActionPerformed

    private void btndimensi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndimensi1ActionPerformed
        txt_area.setText("Panjang\t:2,180 mm"  
                +"\nLebar\t:800 mm" +"\nTinggi\t:1100 mm"+"\nJarak Sumbu Roda :1485 mm"  
                +"\nJarak Terendah ke Tanah :130 mm" +"\nTinggi Tempat Duduk:795 mm" 
                +"\nBerat Bersih :252 Kg" +"\nKapasitas Tangki Bahan Bakar:16,8 Liter");
    }//GEN-LAST:event_btndimensi1ActionPerformed

    private void InfoMotor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMotor1ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelinfo1);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_InfoMotor1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor1);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnmesin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmesin2ActionPerformed
        txt_area2.setText("Tipe Mesin\t:Single Cylinder,4-Stroke,4 Valve DOHC, Liquid cooled engine"  
                +"\nKapasitas :149.16cc" +"\nDiameter x Rangka :57.3 x 57.8 mm" 
                +"\nRasio Kompresi :11.3 : 1" +"\nDaya Maksimum :16.8 kW/9000 rpm" 
                +"\nTorsi Maksimum :14.4 Nm/7000 rpm" +"\nSistem Starter\t:Electric" 
                +"\nTransmisi\t:6 Kecepatan" +"\nType Kopling\t:Wet, Multiplate"
                +"\nSistem Pembakaran :Full Transisterized" +"\nSistem Bahan Bakar :PGM-FI"
                +"\nJenis Bahan Bakar :Petrol" );
    }//GEN-LAST:event_btnmesin2ActionPerformed

    private void btndimensi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndimensi2ActionPerformed
        txt_area2.setText("Panjang\t:1983 mm"  +"\nLebar\t:694 mm" +"\nTinggi\t:1038 mm"
                +"\nJarak Sumbu Roda :1311 mm" 
                +"\nJarak Terendah ke Tanah :130 mm" +"\nTinggi Tempat Duduk:787 mm" 
                +"\nBerat Bersih :135 Kg" +"\nKapasitas Tangki OLI:1,1 Liter");
    }//GEN-LAST:event_btndimensi2ActionPerformed

    private void btnrangka2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangka2ActionPerformed
        // TODO add your handling code here:
        txt_area2.setText("Tipe Rangka :Double Steel Cradle" +"\nSuspensi Depan:Swing Arm"
                +"\nSuspendi Belakang :Telescopic Fork"
                +"\nUkuran Velg Depan : 17 R"+"\nUkuran Velg Belakang : 17 R" 
                +"\nBan Depan :100/80 R17" +"\nBan Belakang :130/70 R17" 
                +"\nJenis Ban : Radial, Tubeless");
    }//GEN-LAST:event_btnrangka2ActionPerformed

    private void btnkembali2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembali2ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor2);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_btnkembali2ActionPerformed

    private void btnrangka3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangka3ActionPerformed
        // TODO add your handling code here:
        txtarea3.setText("Tipe Rangka :Double Steel Cradle"  
                +"\nSuspensi Depan: Telescopic Fork"
                +"\nSuspendi Belakang :MonoShock"
                +"\nUkuran Velg Depan :R19" 
                +"\nUkuran Velg Belakang :R17" 
                +"\nBan Depan :110/80 R19" +"\nBan Belakang :160/60 ZR17" 
                +"\nRem Depan :Disc"+"\nRem Belakang :Disc" +"\nJenis Ban : Runflat");
    }//GEN-LAST:event_btnrangka3ActionPerformed

    private void btnrangka5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangka5ActionPerformed
        txt_area5.setText("Tipe Rangka :Steel Diamond Frame"  
                +"\nSuspensi Depan: Telescopic Fork"
                +"\nSuspendi Belakang :MonoShock"
                +"\nUkuran Velg Depan :R19" 
                +"\nUkuran Velg Belakang :R17" 
                +"\nBan Depan :110/70 R17" +"\nBan Belakang :150/60 R17" 
                +"\nRem Depan :Disc"+"\nRem Belakang :Disc" +"\nJenis Ban : Runflat");
    }//GEN-LAST:event_btnrangka5ActionPerformed

    private void btnmesin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmesin3ActionPerformed
        // TODO add your handling code here:
        txtarea3.setText("Tipe Mesin\t:Parallel Twin Cylinder,4-Stroke,4 Valve DOHC, Liquid cooled engine"  
                +"\nKapasitas Silinder :471cc" +"\nDiameter x Rangka :67 x 66.8 mm" 
                +"\nRasio Kompresi :10.7 : 1" +"\nDaya Maksimum :16.8 kW/8500 rpm" 
                +"\nTorsi Maksimum :44.6 Nm/7000 rpm" +"\nSistem Starter\t:Electric" 
                +"\nPipa Knalpot:Single Exhaust" +"\nKecepatan Maksimum:177 kmph" 
                +"\nTransmisi\t:6 Kecepatan"  +"\nType Kopling\t:Wet, Multiplate"
                +"\nSistem Pembakaran :Full Transisterized" +"\nSistem Bahan Bakar :PGM-FI"
                +"\nJenis Bahan Bakar :Petrol" );
    }//GEN-LAST:event_btnmesin3ActionPerformed

    private void btndimensi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndimensi3ActionPerformed
        // TODO add your handling code here:
        txtarea3.setText("Panjang\t:2156 mm"  +"\nLebar\t:828 mm" +"\nTinggi\t:1412 mm"
                +"\nJarak Sumbu Roda :1443 mm" 
                +"\nJarak Terendah ke Tanah :130 mm" +"\nTinggi Tempat Duduk:834 mm" 
                +"\nBerat Bersih :198 Kg" +"\nKapasitas Tangki OLI:2,4 Liter");
    }//GEN-LAST:event_btndimensi3ActionPerformed

    private void btnkembali3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembali3ActionPerformed
        // TODO add your handling code here:
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor3);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_btnkembali3ActionPerformed

    private void InfoMotor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMotor3ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelinfo3);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_InfoMotor3ActionPerformed

    private void InfoMotor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMotor4ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelinfo4);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_InfoMotor4ActionPerformed

    private void InfoMotor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoMotor5ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelinfo5);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_InfoMotor5ActionPerformed

    private void btnkembali4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembali4ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor4);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_btnkembali4ActionPerformed

    private void btnkembali5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembali5ActionPerformed
        // TODO add your handling code here:
        PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(PanelMotor5);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_btnkembali5ActionPerformed

    private void btnmesin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmesin4ActionPerformed
        txtarea4.setText("Tipe Mesin\t:4-Steps,4 Valve,DOHC"  
                 +"\nDiameter x Rangka :57.3 x 57.8 mm" 
                +"\nRasio Kompresi :11.3 : 1" +"\nDaya Maksimum :16.8 kW/9000 rpm" 
                +"\nTorsi Maksimum :13,8 Nm/7000 rpm" +"\nSistem Starter\t:Kick & Electric" 
                +"\nPipa Knalpot:Single Exhaust" +"\nKecepatan Maksimum:135 kmph" 
                +"\nTransmisi\t:6 Kecepatan"  +"\nType Kopling\t:Wet Clutch, Multiplate, Coil Spring"
                +"\nSistem Pembakaran :Full Transisterized" +"\nSistem Bahan Bakar :PGM-FI"
                +"\nJenis Bahan Bakar :Petrol" );
    }//GEN-LAST:event_btnmesin4ActionPerformed

    private void btnmesin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmesin5ActionPerformed
        txt_area5.setText("Tipe Mesin\t: Liquid cooled Single Cylinder"  
                +"\nKapasitas  :286cc" +"\nDiameter x Rangka :76 x 63 mm" 
                +"\nRasio Kompresi :10.7 : 1" +"\nDaya Maksimum :23.1 kW/8500 rpm" 
                +"\nTorsi Maksimum :27,5 Nm/7500 rpm" +"\nSistem Starter\t:Electric" 
                +"\nPipa Knalpot:Single Exhaust" +"\nKecepatan Maksimum:177 kmph" 
                +"\nTransmisi\t:6 Kecepatan"  +"\nType Kopling\t:Wet, Multiplate"
                +"\nSistem Pembakaran :Full Transisterized" +"\nSistem Bahan Bakar :PGM-FI"
                +"\nJenis Bahan Bakar :Bensin" );
    }//GEN-LAST:event_btnmesin5ActionPerformed

    private void btndimensi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndimensi4ActionPerformed
        // TODO add your handling code here:
        txtarea4.setText("Panjang\t:2156 mm"  +"\nLebar\t:828 mm" +"\nTinggi\t:1412 mm"
                +"\nJarak Sumbu Roda :1443 mm" 
                +"\nJarak Terendah ke Tanah :130 mm" +"\nTinggi Tempat Duduk:834 mm" 
                +"\nBerat Bersih :198 Kg" +"\nKapasitas Tangki OLI:2,4 Liter");
    }//GEN-LAST:event_btndimensi4ActionPerformed

    private void btndimensi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndimensi5ActionPerformed
        txt_area5.setText("Panjang\t:2012 mm"  +"\nLebar\t:802 mm" +"\nTinggi\t:1052 mm"
                +"\nJarak Sumbu Roda :1352 mm" +"\nTinggi Tempat Duduk:799 mm" 
                +"\nBerat Bersih :143 Kg" +"\nKapasitas Tangki :10 Liter");
    }//GEN-LAST:event_btndimensi5ActionPerformed

    private void btnrangka4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrangka4ActionPerformed
        txtarea4.setText("Suspensi Depan: Telescopic Fork"
                +"\nSuspendi Belakang :Swing Arm"
                +"\nUkuran Velg Depan :R17" 
                +"\nUkuran Velg Belakang :R17" 
                +"\nBan Depan :100/80 R17" +"\nBan Belakang :130/70 R17" 
                +"\n Rem Depan :Disc"+"\n Rem Belakang :Disc" +"\nJenis Ban : Radial,Tubeless");
    }//GEN-LAST:event_btnrangka4ActionPerformed

    private void btn_ServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ServiceActionPerformed
            PanelMotor.removeAll();
            PanelMotor.repaint();
            PanelMotor.revalidate();
            
            PanelMotor.add(panelsearch);
            PanelMotor.repaint();
            PanelMotor.revalidate();
    }//GEN-LAST:event_btn_ServiceActionPerformed

    private void txt_cariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cariKeyReleased
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_cari.getText().trim()));
    }//GEN-LAST:event_txt_cariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBack2;
    private javax.swing.JButton BtnBack3;
    private javax.swing.JButton BtnBack4;
    private javax.swing.JButton BtnBack5;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton BtnNext1;
    private javax.swing.JButton BtnNext2;
    private javax.swing.JButton BtnNext3;
    private javax.swing.JButton BtnNext4;
    private javax.swing.JButton BtnPromo;
    private javax.swing.JButton InfoMotor1;
    private javax.swing.JButton InfoMotor2;
    private javax.swing.JButton InfoMotor3;
    private javax.swing.JButton InfoMotor4;
    private javax.swing.JButton InfoMotor5;
    private javax.swing.JPanel PanelMotor;
    private javax.swing.JPanel PanelMotor1;
    private javax.swing.JPanel PanelMotor2;
    private javax.swing.JPanel PanelMotor3;
    private javax.swing.JPanel PanelMotor4;
    private javax.swing.JPanel PanelMotor5;
    private javax.swing.JPanel PnlKiriMotor;
    private javax.swing.JButton btn_Service;
    private javax.swing.JButton btndimensi1;
    private javax.swing.JButton btndimensi2;
    private javax.swing.JButton btndimensi3;
    private javax.swing.JButton btndimensi4;
    private javax.swing.JButton btndimensi5;
    private javax.swing.JButton btnkembali2;
    private javax.swing.JButton btnkembali3;
    private javax.swing.JButton btnkembali4;
    private javax.swing.JButton btnkembali5;
    private javax.swing.JButton btnmesin1;
    private javax.swing.JButton btnmesin2;
    private javax.swing.JButton btnmesin3;
    private javax.swing.JButton btnmesin4;
    private javax.swing.JButton btnmesin5;
    private javax.swing.JButton btnrangka1;
    private javax.swing.JButton btnrangka2;
    private javax.swing.JButton btnrangka3;
    private javax.swing.JButton btnrangka4;
    private javax.swing.JButton btnrangka5;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelinfo1;
    private javax.swing.JPanel panelinfo2;
    private javax.swing.JPanel panelinfo3;
    private javax.swing.JPanel panelinfo4;
    private javax.swing.JPanel panelinfo5;
    private javax.swing.JPanel panelsearch;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextArea txt_area2;
    private javax.swing.JScrollPane txt_area3;
    private javax.swing.JTextArea txt_area5;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextArea txtarea3;
    private javax.swing.JTextArea txtarea4;
    // End of variables declaration//GEN-END:variables
}
