
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class PesanMobil2 extends javax.swing.JFrame {

    /**
     * Creates new form tes
     */
    int DP, total, total2, jumlah, harga,pokok,bunga,otr,bunga2;
    public PesanMobil2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_OTR = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_tipe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_warna = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rb_cash = new javax.swing.JRadioButton();
        rb_kredit = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_NIK = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_HP = new javax.swing.JTextField();
        PanelKanan = new javax.swing.JPanel();
        panel_mobil = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        panel_kredit = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_bunga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_bunga2 = new javax.swing.JTextField();
        txttotal_hutang = new javax.swing.JTextField();
        txt_angsuran = new javax.swing.JTextField();
        txt_uang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_pokok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_DP1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_DP2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rb_enor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btn_hitung = new javax.swing.JButton();
        txt_bulan = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        cbjenis_angsuran = new javax.swing.JComboBox<>();
        btn_cetak = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();
        BtnExit = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HONDA.com");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_area.setColumns(20);
        txt_area.setRows(5);
        jScrollPane2.setViewportView(txt_area);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 191, 319, 290));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Harga OTR");

        txt_OTR.setText(" ");
        txt_OTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_OTRActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIPE");

        cb_tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "ODYSSEY", "BRIO SATYA", "CR-V", "BR-V", "JAZZ" }));
        cb_tipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_tipeActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Varian Warna");

        cb_warna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "Merah", "Kuning", "Hitam", " " }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jenis Pembayaran");

        rb_cash.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rb_cash);
        rb_cash.setForeground(new java.awt.Color(255, 255, 255));
        rb_cash.setText("CASH");
        rb_cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cashActionPerformed(evt);
            }
        });

        rb_kredit.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(rb_kredit);
        rb_kredit.setForeground(new java.awt.Color(255, 255, 255));
        rb_kredit.setText("KREDIT");
        rb_kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_kreditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(rb_cash)
                        .addGap(18, 18, 18)
                        .addComponent(rb_kredit)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_tipe, 0, 159, Short.MAX_VALUE)
                            .addComponent(cb_warna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_OTR))
                        .addContainerGap(54, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cb_tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_OTR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rb_cash)
                    .addComponent(rb_kredit))
                .addGap(136, 136, 136))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 340, 140));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nama Lengkap");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("No.HP");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("ALAMAT");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("NIK");

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        txt_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_namaKeyTyped(evt);
            }
        });

        txt_NIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NIKActionPerformed(evt);
            }
        });
        txt_NIK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NIKKeyTyped(evt);
            }
        });

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        txt_HP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HPActionPerformed(evt);
            }
        });
        txt_HP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_HPKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_HP, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                        .addComponent(txt_alamat)
                        .addComponent(txt_NIK))
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txt_NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_HP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 140));

        PanelKanan.setLayout(new java.awt.CardLayout());

        panel_mobil.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Bodoni Bk BT", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/AS.png"))); // NOI18N

        javax.swing.GroupLayout panel_mobilLayout = new javax.swing.GroupLayout(panel_mobil);
        panel_mobil.setLayout(panel_mobilLayout);
        panel_mobilLayout.setHorizontalGroup(
            panel_mobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        panel_mobilLayout.setVerticalGroup(
            panel_mobilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mobilLayout.createSequentialGroup()
                .addGap(0, 90, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        PanelKanan.add(panel_mobil, "card3");

        panel_kredit.setBackground(new java.awt.Color(0, 0, 0));
        panel_kredit.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Uang Muka");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Angsuran per Bulan");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total Hutang");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bunga");

        txt_bunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bungaActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("%");

        txt_bunga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bunga2ActionPerformed(evt);
            }
        });

        txttotal_hutang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotal_hutangActionPerformed(evt);
            }
        });

        txt_angsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_angsuranActionPerformed(evt);
            }
        });

        txt_uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uangActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pokok Hutang");

        txt_pokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_pokokActionPerformed(evt);
            }
        });
        txt_pokok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_pokokKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOWN PAYMENT");

        txt_DP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DP1ActionPerformed(evt);
            }
        });
        txt_DP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DP1KeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("%");

        txt_DP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DP2ActionPerformed(evt);
            }
        });
        txt_DP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_DP2KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Jenis Angsuran");

        rb_enor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "1 TAHUN", "2 TAHUN", "3 TAHUN" }));
        rb_enor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_enorActionPerformed(evt);
            }
        });
        rb_enor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rb_enorKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TENOR");

        btn_hitung.setText("HITUNG");
        btn_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hitungActionPerformed(evt);
            }
        });
        btn_hitung.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_hitungKeyReleased(evt);
            }
        });

        txt_bulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_bulanActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("BULAN");

        cbjenis_angsuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "APDM", "APDB" }));
        cbjenis_angsuran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenis_angsuranActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_kreditLayout = new javax.swing.GroupLayout(panel_kredit);
        panel_kredit.setLayout(panel_kreditLayout);
        panel_kreditLayout.setHorizontalGroup(
            panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kreditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kreditLayout.createSequentialGroup()
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_kreditLayout.createSequentialGroup()
                                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_kreditLayout.createSequentialGroup()
                                        .addComponent(txt_bunga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_kreditLayout.createSequentialGroup()
                                            .addComponent(txt_DP1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_DP2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txt_pokok, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_kreditLayout.createSequentialGroup()
                                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_bunga2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel_kreditLayout.createSequentialGroup()
                                        .addComponent(rb_enor, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addComponent(btn_hitung))
                                .addGap(34, 34, 34))))
                    .addGroup(panel_kreditLayout.createSequentialGroup()
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_kreditLayout.createSequentialGroup()
                                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))
                                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_kreditLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(cbjenis_angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_kreditLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_uang, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                            .addComponent(txt_angsuran, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                            .addComponent(txttotal_hutang))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_kreditLayout.setVerticalGroup(
            panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_kreditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_DP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_DP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kreditLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbjenis_angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(btn_hitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txttotal_hutang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_kreditLayout.createSequentialGroup()
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rb_enor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_bunga2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_bunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)))))
                .addGap(9, 9, 9)
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_angsuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_kreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_uang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        PanelKanan.add(panel_kredit, "card2");

        jPanel1.add(PanelKanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 188, 341, 290));

        btn_cetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examples/1Y.png"))); // NOI18N
        btn_cetak.setText("CETAK");
        btn_cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cetakActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, 40));

        BtnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1111111.png"))); // NOI18N
        BtnHome.setText("HOME");
        BtnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(BtnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, 40));

        BtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/15151.png"))); // NOI18N
        BtnExit.setText("EXIT");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        jPanel1.add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 100, 40));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Bodoni Bk BT", 1, 20)); // NOI18N
        jLabel21.setText("FORM PEMESANAN MOBIL");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 11, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_tipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_tipeActionPerformed
        if(cb_tipe.getSelectedItem().equals(cb_tipe)){
        buttonGroup1.clearSelection();
        txt_OTR.setText("");
    }
        else if(cb_tipe.getSelectedItem().equals("ODYSSEY")){
            txt_OTR.setText(String.valueOf("260000000"));
        
        }
        else if(cb_tipe.getSelectedItem().equals("BRIO SATYA")){
            txt_OTR.setText(String.valueOf("131500000"));
         }
        else if(cb_tipe.getSelectedItem().equals("CR-V")){
            txt_OTR.setText(String.valueOf("250000000"));
        }
        else if(cb_tipe.getSelectedItem().equals("BR-V")){
            txt_OTR.setText(String.valueOf("226500000"));
        }
        else {
            txt_OTR.setText(String.valueOf("232500000"));

        }
    }//GEN-LAST:event_cb_tipeActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_NIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NIKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NIKActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_HPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HPActionPerformed

    private void rb_kreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_kreditActionPerformed
        // TODO add your handling code here:
            PanelKanan.removeAll();
            PanelKanan.repaint();
            PanelKanan.revalidate();
            
            PanelKanan.add(panel_kredit);
            PanelKanan.repaint();
            PanelKanan.revalidate();
    }//GEN-LAST:event_rb_kreditActionPerformed

    private void rb_enorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_enorActionPerformed
        // TODO add your handling code here:
        if(rb_enor.getSelectedItem().equals(rb_enor)){
        buttonGroup1.clearSelection();
        
        }
        else if(rb_enor.getSelectedItem().equals("1 TAHUN")){
            txt_bulan.setText(String.valueOf("12"));
            txt_bunga.setText(String.valueOf("4"));
            bunga=Integer.parseInt(txt_bunga.getText());
            otr = Integer.parseInt(txt_OTR.getText());
                total=otr*bunga/100;
                txt_bunga2.setText(String.valueOf(total));
        }
        else if(rb_enor.getSelectedItem().equals("2 TAHUN")){
            txt_bulan.setText(String.valueOf("24"));
            txt_bunga.setText(String.valueOf("5"));
            bunga=Integer.parseInt(txt_bunga.getText());
            otr = Integer.parseInt(txt_OTR.getText());
                total=otr*bunga/100;
                txt_bunga2.setText(String.valueOf(total));
        }
        else {
            txt_bulan.setText(String.valueOf("36"));
            txt_bunga.setText(String.valueOf("6"));
            bunga=Integer.parseInt(txt_bunga.getText());
            otr = Integer.parseInt(txt_OTR.getText());
                total=otr*bunga/100;
                txt_bunga2.setText(String.valueOf(total));
        }
    }//GEN-LAST:event_rb_enorActionPerformed

    private void txt_pokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_pokokActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_pokokActionPerformed

    private void txt_uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uangActionPerformed

    private void txt_angsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_angsuranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_angsuranActionPerformed

    private void txt_bunga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bunga2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_bunga2ActionPerformed

    private void txt_OTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_OTRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_OTRActionPerformed

    private void txt_bungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bungaActionPerformed
        // TODO add your handling code here:

    
    }//GEN-LAST:event_txt_bungaActionPerformed

    private void txt_DP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DP1ActionPerformed
        // TODO add your handling code here:
        DP=Integer.parseInt(txt_DP1.getText());
        harga = Integer.parseInt(txt_OTR.getText());
        
                total=DP/100*harga;
                txt_DP2.setText(String.valueOf(total));
                pokok = Integer.parseInt(txt_DP2.getText());
                total2= harga-pokok;
                txt_pokok.setText(String.valueOf(total2));
    }//GEN-LAST:event_txt_DP1ActionPerformed

    private void txt_DP2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DP2KeyReleased
    }//GEN-LAST:event_txt_DP2KeyReleased

    private void txt_DP1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DP1KeyReleased
        // TODO add your handling code here:
        int a,b,c,d,e;
        a=Integer.valueOf(txt_OTR.getText());
        b=Integer.valueOf(txt_DP1.getText());
        
        c=a/100*b;
        txt_DP2.setText(""+c); 
        d=Integer.valueOf(txt_DP2.getText());
        e=a-d;
        txt_pokok.setText(""+e);
      
    }//GEN-LAST:event_txt_DP1KeyReleased

    private void txt_pokokKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_pokokKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_pokokKeyReleased

    private void rb_enorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rb_enorKeyReleased
        // TODO add your handling code here:
        int a,b,c;
         
        a=Integer.valueOf(txt_DP1.getText());
        b=Integer.valueOf(txt_OTR.getText());
        c=b/100*a;
        txt_bunga2.setText(""+c);
    }//GEN-LAST:event_rb_enorKeyReleased

    private void btn_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hitungActionPerformed
        // TODO add your handling code here:
        int pokokhutang,bulan,hutang,uangmuka,angsuran;
        
        pokokhutang= Integer.parseInt(txt_pokok.getText());
        bunga2 = Integer.parseInt(txt_bunga2.getText());
        hutang= pokokhutang+bunga2;
        txttotal_hutang.setText(""+hutang);
        
        bulan=Integer.parseInt(txt_bulan.getText());
        hutang=Integer.parseInt(txttotal_hutang.getText());
        angsuran= hutang/bulan;
        txt_angsuran.setText(""+angsuran);
        
        if(cbjenis_angsuran.getSelectedItem().equals(cbjenis_angsuran)){
        buttonGroup1.clearSelection();
        cbjenis_angsuran.setSelectedItem(-1);
        txt_bunga.setText("");
        }
        else if(cbjenis_angsuran.getSelectedItem().equals("APDM")){
           angsuran=Integer.parseInt(txt_angsuran.getText());
            DP= Integer.parseInt(txt_DP2.getText());
            uangmuka= angsuran+DP;
            txt_uang.setText(""+uangmuka);
        }
        else if(cbjenis_angsuran.getSelectedItem().equals("APDB")){
            DP= Integer.parseInt(txt_DP2.getText());
            uangmuka=DP;
            txt_uang.setText(""+uangmuka);
        }
        
        
    }//GEN-LAST:event_btn_hitungActionPerformed

    private void btn_cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cetakActionPerformed
        // TODO add your handling code here:
        String Nama1 = txt_nama.getText();
        String Alamat1 = txt_alamat.getText();
        String nik = txt_NIK.getText();
        String hp = txt_HP.getText();
        String tipe = (String)cb_tipe.getSelectedItem();
        String Harga = txt_OTR.getText();
        String Warna = (String)cb_warna.getSelectedItem();
        String dp = txt_DP2.getText();
        String Pokok = txt_pokok.getText();
        String tenor = (String)rb_enor.getSelectedItem();
        String Bunga = txt_bunga2.getText();
        String jenis = (String)cbjenis_angsuran.getSelectedItem();
        String hutang = txttotal_hutang.getText();
        String angsuran = txt_angsuran.getText();
        String uang = txt_uang.getText();
        
        if(rb_cash.isSelected()){
        txt_area.setText("Nama Lengkap\t:" +Nama1 +"\nAlamat\t:" +Alamat1 +"\nNIK\t:"+nik +"\nNo.HP\t:"+hp 
                +"\nTipe\t:"+tipe +"\nVarian Warna\t:"+Warna +"\nHarga OTR\t:"+Harga  );
        }
        else if(rb_kredit.isSelected()){
        txt_area.setText("Nama Lengkap\t:" +Nama1 +"\nAlamat\t:" +Alamat1 +"\nNIK\t:"+nik +"\nNo.HP\t:"+hp 
                +"\nTipe\t:"+tipe +"\nVarian Warna\t:"+Warna +"\nHarga OTR\t:"+Harga +"\n============================" 
                +"\nDown Payment\t:"+dp +"\nPokok Hutang\t:"+Pokok +"\nTENOR\t:"+tenor +"\nBunga\t:"+Bunga 
                +"\nJenis Angsuran\t:"+jenis +"\nTotal Hutang\t:"+hutang +"\nAngsuran per Bulan\t:"+angsuran 
                +"\nTotal Uang Muka\t:"+uang );
        }
    }//GEN-LAST:event_btn_cetakActionPerformed

    private void cbjenis_angsuranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenis_angsuranActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbjenis_angsuranActionPerformed

    private void txt_DP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DP2ActionPerformed

    private void txttotal_hutangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotal_hutangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotal_hutangActionPerformed

    private void btn_hitungKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_hitungKeyReleased
       
    }//GEN-LAST:event_btn_hitungKeyReleased

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        int dialogBtn = JOptionPane.OK_CANCEL_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin Akan Keluar?","PERINGATAN",dialogBtn);
        if (dialogResult==0){
            System.exit(0);
        }else{
        }              // TODO add your handling code here:
    }//GEN-LAST:event_BtnExitActionPerformed

    private void BtnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHomeActionPerformed
        // TODO add your handling code here:
        home n= new home();
        n.setVisible(true);
    }//GEN-LAST:event_BtnHomeActionPerformed

    private void txt_bulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_bulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_bulanActionPerformed

    private void rb_cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cashActionPerformed
        PanelKanan.removeAll();
            PanelKanan.repaint();
            PanelKanan.revalidate();
            
            PanelKanan.add(panel_mobil);
            PanelKanan.repaint();
            PanelKanan.revalidate();
    }//GEN-LAST:event_rb_cashActionPerformed

    private void txt_namaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isAlphabetic(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_namaKeyTyped

    private void txt_NIKKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NIKKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        } 
    }//GEN-LAST:event_txt_NIKKeyTyped

    private void txt_HPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_HPKeyTyped
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txt_HPKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesanMobil2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesanMobil2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesanMobil2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesanMobil2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesanMobil2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnHome;
    private javax.swing.JPanel PanelKanan;
    private javax.swing.JButton btn_cetak;
    private javax.swing.JButton btn_hitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_tipe;
    private javax.swing.JComboBox<String> cb_warna;
    private javax.swing.JComboBox<String> cbjenis_angsuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel_kredit;
    private javax.swing.JPanel panel_mobil;
    private javax.swing.JRadioButton rb_cash;
    private javax.swing.JComboBox<String> rb_enor;
    private javax.swing.JRadioButton rb_kredit;
    private javax.swing.JTextField txt_DP1;
    private javax.swing.JTextField txt_DP2;
    private javax.swing.JTextField txt_HP;
    private javax.swing.JTextField txt_NIK;
    private javax.swing.JTextField txt_OTR;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_angsuran;
    private javax.swing.JTextArea txt_area;
    private javax.swing.JTextField txt_bulan;
    private javax.swing.JTextField txt_bunga;
    private javax.swing.JTextField txt_bunga2;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_pokok;
    private javax.swing.JTextField txt_uang;
    private javax.swing.JTextField txttotal_hutang;
    // End of variables declaration//GEN-END:variables
}
